name: Build RPD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.13']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install APT dependencies
        run: sudo apt install -y libglw1-mesa-dev libglfw3-dev libx11-dev libxcursor-dev libxinerama-dev libxxf86vm-dev libxi-dev
      - name: Install Fyne-Cross
        run: go install github.com/fyne-io/fyne-cross@v1.1.3
      - name: Install Go dependencies
        run: go get .
      - name: Build Code
        run: sh ./build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RPD
          path: ./build/
